### ISSUE TITLE
Wireframing

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#4]
- a basic wireframe of the form (questions)
- design for skills wheel will be based on what is displayed in the PDF Manual

**Comment by Jbarget** [comment]
The aim is to have collapsable tabs for each of the 6 sections

![img_5544](https://cloud.githubusercontent.com/assets/11725595/13215446/3e5cfaca-d94d-11e5-8359-36e70d5bd5c6.JPG)

**Comment by ICHelen** [comment]
This looks great! 

One thing I spoke to Ines about, which it would be great if you were able to look at at this stage is TAs being able to view their previous inputs when inputting latest data. So... if a TA is working with Child X and had answered all Qs relating to his social skill abilities in September, when he/she came to input data on child X's skills 3 months later, in January, he/she is able to see which face they'd clicked on previously, so that they have a benchmark with which to work from and assess whether child X has stayed the same, improved or deteriorated. Maybe we could have something which shows the previous score when you click on the Q, or something similar?

I've no idea how complicated this would be but I have September and January data from 3 schools and 58 pupils if you'd like a small sample to trial this with? No problem if you think it's outside the remit at this stage though- a suggestion!

Helen

**Comment by iteles** [comment]
@Jbarget @Danwhy Agree, I like the idea of the collapsible sections. We'll need to make it very obvious that you need to open the next section in order to answer it both in terms of user experience and maybe with an alert that keeps people from abandoning a half-filled questionnaire?

@ICHelen This really is a great idea, but is outside of the scope for this iteration. Having said that, what we're doing is saving all of the data captured in the questionnaire to a database - this means that any data you capture in April can be relatively easily utilised to make this feature available in the next iteration.

**Comment by ICHelen** [comment]
@iteles Yes- I understand it may be out of the remit at this stage. I presume there's nothing stopping me from inputting data from my first two data collection points for each child- once the prototype is up and running? Then we could look at making that data available when TAs input future data. I'm really keen to try and have this function available when testing with TAs. I just know how much they valued seeing their baselines when filling in the Jan wheels. Maybe something to discuss at our end of project meet up!

**Comment by iteles** [comment]
@ICHelen At the moment the process for inputting data is the questionnaire and this would be very labour intensive for you! We can have a think about what the simplest way to bring this data in would be and discuss it in more detail with Zing.

Also, correct me if I'm wrong but won't they be able to see their paper-based wheels from Jan when they're filling out the April ones? (I imagine the bigger problem to be the next checkpoint when the only record of April's wheels are digital).

**Comment by iteles** [comment]
@Jbarget @Danwhy I'm currently putting some thoughts together on some final styling improvements. I'll add them to our gitter channel for discussion and then we can add the proposal here

**Comment by iteles** [comment]
Higher fidelity designs:

<img width="1056" alt="inclusive-classrooms-skillswheel-proposed-design-with-comments" src="https://cloud.githubusercontent.com/assets/4185328/13460351/ec419d78-e071-11e5-92bb-66e5cfa98f62.png">
![inclusive-classrooms-skillswheel-proposed-design-open-questions](https://cloud.githubusercontent.com/assets/4185328/13460352/ec45a710-e071-11e5-9539-16d9810b37ff.png)
