### ISSUE TITLE
Summary of 20/2 call

### ISSUE THREAD

**Issue by samhstn** [InclusiveClassrooms/skills-wheel#4]
Each school has 1-4 groups running at a time, which consist of: years 3 - 6 and 5 - 10 students
Data is collected at 4 points throught the year from Sept and the start of each subsequent term
Every student **must** be a part of a group
TAs can create groups and children and these can only be edited by those TAs and the admin
Previous term answers should be viewable by button click (as a "do you need some help?" button)
Showing previous wheel that the end of a survey would be a nice extra feature
A TA may want to view the wheels and print them off
For the admin the data should be filterable by: year, group, individual, school and ta

20 schools will be using this with at least one group each of 10 students
The spreadsheet will get a bit unmaintainable and an internal way of viewing data would also be a nice feature

**Comment by harrygfox** [comment]
@shouston3 @jackcarlisle 

> Previous term answers should be viewable by button click (as a "do you need some help?" button)

I'd just like to clarify / query a couple of points about this one. 

There are **two places** to see the previous answers to an assessment: 
- The Student's Profile
- The Assessment Form (as I, the TA, am conducting an assessment)

_I assume this line refers to the latter of the two._ 

This should be on a **per-question** basis, no?

The UX effect being that we want the TA to assess the student _as they see them right now_ but we want to also allow the TA to **check** what they previously answered for **this question** to make sure they aren't over or under scoring the student.

I like that this feature must be toggled for each question because it discourages the _"wants-to-fill-in-this-form-as-quickly-as-possible"_ from running down the list and repeating last assessment's scores +1 or something.

**Comment by iteles** [comment]
@harrygfox That's exactly what we discussed and agreed with Helen on this call :+1:

**Comment by jackcarlisle** [comment]
@harrygfox Yep! What @iteles said ✅

**Comment by jackcarlisle** [comment]
Closing as all points have been extracted into issues
