### ISSUE TITLE
Host app on Heroku

### ISSUE THREAD

**Issue by Danwhy** [InclusiveClassrooms/skills-wheel#50]
linked to #19

**Comment by iteles** [comment]
Could we create a shared google doc to contain usernames and passwords for things like our heroku login please?

**Comment by Jbarget** [comment]
We can set up helen/inclusive classrooms with a heroku account and then transfer ownership on handover? we'd need to know an email address that she would want to use and a password. Or she could set one up herself, either or is fine with us!

Since we wouldnt want to be sharing our heroku  passwords with her, no offence intended

**Comment by iteles** [comment]
Oh, you set them on your own accounts rather than a test inclusiveclassrooms account, got it! Transferring ownership makes sense.

**Comment by iteles** [comment]
Complete, can we please add the detail into the readme?
